admin_dashboard:
  path:     /
  defaults: { _controller: admin.dashboard:indexAction }

file_upload:
  path: /upload
  defaults: { _controller: file.upload:indexAction }
  methods: [POST]

post_post:
    path: /post
    defaults: { _controller: post.controller:postAction }
    methods: [POST]

put_post:
    path: /post/{id}
    defaults: { _controller: post.controller:putAction }
    requirements:
        page: '\d+'
    methods: [PUT]

get_post:
    path: /post/{id}
    defaults: { _controller: post.controller:getAction }
    requirements:
        page: '\d+'
    methods: [GET]

get_post_list:
    path: /post-list
    defaults: { _controller: post.list.controller:getPostListAction }
