services:
    admin.dashboard:
        class: AdminBundle\Controller\DashBoardController
        arguments: ["@templating"]

    file.upload:
        class: AdminBundle\Controller\UploadFile

    post.controller:
        class: AdminBundle\Controller\PostController
        arguments: ["@form.factory", "@request_stack", "@doctrine.orm.default_entity_manager"]

    post.list.controller:
        class: AdminBundle\Controller\PostListController
        arguments: ["@doctrine.orm.default_entity_manager"]
