services:
    admin.dashboard:
        class: AdminBundle\Controller\DashBoardController
        arguments: ["@templating"]

    file.upload.controller:
        class: AdminBundle\Controller\FileUploadController
        arguments: ["%img_domain%", "%img_path%"]

    post.controller:
        class: AdminBundle\Controller\PostController
        arguments: ["@form.factory", "@request_stack", "@doctrine.orm.default_entity_manager"]

    post.list.controller:
        class: AdminBundle\Controller\PostListController
        arguments: ["@doctrine.orm.default_entity_manager"]
