services:
  admin.dashboard:
    class: AdminBundle\Controller\DashBoardController
    arguments: ["@templating"]

  create.post:
    class: AdminBundle\Controller\CreatePostController
    arguments: ["@templating"]