<?php

namespace FrontendBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPostList($page)
    {
        if ($page > 0) {
            $offset = ($page - 1) * 10;
        } else {
            $offset = 0;
        }
        return $this->getEntityManager()
                    ->createQuery(
                        'SELECT    p
                         FROM      FrontendBundle:Post p
                         ORDER BY  p.id DESC'
                    )
                    ->setFirstResult($offset)
                    ->setMaxResults(11)
                    ->getArrayResult();
    }

    public function getPost($id)
    {
        return $this->getEntityManager()
                    ->createQuery(
                        'SELECT    p
                         FROM      FrontendBundle:Post p
                         WHERE     p.id = :id'
                    )
                    ->setParameter('id', $id)
                    ->getArrayResult();
    }

    public function getTopPosts()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT    p
                 FROM      FrontendBundle:Post p
                 ORDER BY  p.id'
            )
            ->setMaxResults(5)
            ->getArrayResult();
    }
}
