<?php

namespace FrontendBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPosts($startRank, $endRank)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT     p
                 FROM       FrontendBundle:Post p
                 WHERE      p.rank
                 BETWEEN    :startRank AND :endRank + 1
                 ORDER BY   p.rank ASC'
            )
            ->setParameters([
                'startRank' => $startRank,
                'endRank'   => $endRank,
            ])
            ->getResult();
    }
}
