homepage:
    path:     /
    defaults: { _controller: home.page:indexAction , page: 1}

pagination:
    path: /page/{page}
    defaults: { _controller: home.page:indexAction }
    requirements:
        page:  \d+

post_page:
    path: post/{name}
    defaults: { _controller: post.page:indexAction }

author_page:
    path: author
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    FrontendBundle:AuthorPage:index.html.twig
