services:
    home.page:
        class: FrontendBundle\Controller\HomePageController
        arguments: ["@doctrine.orm.default_entity_manager", "@templating"]

    post.listener:
        class: FrontendBundle\EventListener\PostListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
        arguments: ["@image.thumbnail.service"]

    post.page:
        class: FrontendBundle\Controller\PostPageController
        arguments: ["@doctrine.orm.default_entity_manager", "@templating"]
